/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.helmo.gbeditor;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Program classUnderTest = new Program();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
